/** Standard ERP record shape returned by every import. */
export const STANDARD_RECORD = {
  invoiceNo: '',
  invoiceDate: '',
  partyName: '',
  partyType: '',
  mobile: '',
  city: '',
  gstin: '',
  itemName: '',
  batchNo: '',
  expiryDate: '',
  quantity: 0,
  rate: 0,
  discount: 0,
  gstPercent: 0,
  taxableAmount: 0,
  gstAmount: 0,
  totalAmount: 0,
  expenseTitle: '',
  category: '',
  paymentMode: '',
  notes: '',
}

/** Mandatory fields for invoice-style imports. */
export const MANDATORY_FIELDS = ['itemName' || 'partyname']

/** Strongly recommended fields — reported as warnings when missing. */
export const RECOMMENDED_FIELDS = ['invoiceNo', 'invoiceDate', 'quantity']

export const ACCEPTED_EXTENSIONS = ['.xlsx', '.xls', '.csv', '.json']
export const ACCEPTED_MIME_TYPES = [
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-excel',
  'text/csv',
  'application/csv',
  'application/json',
  'text/plain',
]

export const MAX_ROWS = 50000
export const PREVIEW_ROW_COUNT = 20
export const CHUNK_SIZE = 1000

/**
 * Smart column alias map — keys are normalized header tokens, values are standard fields.
 * Supports Marg ERP, Tally-style, and generic export headers.
 */
export const FIELD_ALIASES = {
  invoiceno: 'invoiceNo',
  invoicenumber: 'invoiceNo',
  invoicenum: 'invoiceNo',
  invno: 'invoiceNo',
  invnumber: 'invoiceNo',
  billno: 'invoiceNo',
  billnumber: 'invoiceNo',
  invoicedate: 'invoiceDate',
  invdate: 'invoiceDate',
  billdate: 'invoiceDate',
  date: 'invoiceDate',
  partyname: 'partyName',
  party: 'partyName',
  customername: 'partyName',
  clientname: 'partyName',
  buyername: 'partyName',
  suppliername: 'partyName',
  vendorname: 'partyName',
  name: 'partyName',
  partytype: 'partyType',
  type: 'partyType',
  mobile: 'mobile',
  mobileno: 'mobile',
  phoneno: 'mobile',
  phone: 'mobile',
  contact: 'mobile',
  contactno: 'mobile',
  city: 'city',
  place: 'city',
  gstin: 'gstin',
  gstno: 'gstin',
  gstnumber: 'gstin',
  itemname: 'itemName',
  productname: 'itemName',
  product: 'itemName',
  item: 'itemName',
  description: 'itemName',
  particulars: 'itemName',
  batchno: 'batchNo',
  batch: 'batchNo',
  batchnumber: 'batchNo',
  lotno: 'batchNo',
  expirydate: 'expiryDate',
  expiry: 'expiryDate',
  expdate: 'expiryDate',
  exp: 'expiryDate',
  quantity: 'quantity',
  qty: 'quantity',
  qnty: 'quantity',
  units: 'quantity',
  stock: 'quantity',
  closingstock: 'quantity',
  openingstock: 'quantity',
  rate: 'rate',
  price: 'rate',
  unitrate: 'rate',
  mrp: 'rate',
  salerate: 'rate',
  salesrate: 'rate',
  purchaserate: 'rate',
  purrate: 'rate',
  discount: 'discount',
  disc: 'discount',
  discountpercent: 'discount',
  discountamount: 'discount',
  gstpercent: 'gstPercent',
  gstrate: 'gstPercent',
  gst: 'gstPercent',
  gstpercentage: 'gstPercent',
  taxpercent: 'gstPercent',
  taxrate: 'gstPercent',
  cgstsgst: 'gstPercent',
  igst: 'gstPercent',
  taxableamount: 'taxableAmount',
  taxablevalue: 'taxableAmount',
  taxable: 'taxableAmount',
  amount: 'taxableAmount',
  subtotal: 'taxableAmount',
  gstamount: 'gstAmount',
  taxamount: 'gstAmount',
  totaltax: 'gstAmount',
  totalamount: 'totalAmount',
  total: 'totalAmount',
  grandtotal: 'totalAmount',
  netamount: 'totalAmount',
  hsn: 'hsnCode',
  hsncode: 'hsnCode',
  hsnsac: 'hsnCode',
  expensetitle: 'expenseTitle',
  expensename: 'expenseTitle',
  expense: 'expenseTitle',
  title: 'expenseTitle',
  narration: 'expenseTitle',
  category: 'category',
  expensecategory: 'category',
  paymentmode: 'paymentMode',
  mode: 'paymentMode',
  notes: 'notes',
  note: 'notes',
  remarks: 'notes',
  balance: 'balance',
  openingbalance: 'balance',
  drcr: 'drCr',
  debitcredit: 'drCr',
}

/** Marg ERP export headers mapped explicitly for documentation and priority matching. */
export const MARG_ERP_FIELD_MAP = {
  'Item Name': 'itemName' ,
  'Batch': 'batchNo',
  'Expiry': 'expiryDate',
  'MRP': 'rate',
  'Sale Rate': 'rate',
  'Sales Rate': 'rate',
  'Purchase Rate': 'purchaseRate',
  'HSN': 'hsnCode',
  'HSN Code': 'hsnCode',
  'GST': 'gstPercent',
  'GST %': 'gstPercent',
  'Stock': 'quantity',
  'Closing Stock': 'quantity',
  'Opening Stock': 'quantity',
}

export const DEFAULT_RECORD_VALUES = {
  invoiceNo: '',
  invoiceDate: '',
  partyName: '',
  partyType: '',
  mobile: '',
  city: '',
  gstin: '',
  itemName: '',
  batchNo: '',
  expiryDate: '',
  quantity: 0,
  rate: 0,
  discount: 0,
  gstPercent: 0,
  taxableAmount: 0,
  gstAmount: 0,
  totalAmount: 0,
  purchaseRate: 0,
  hsnCode: '',
  expenseTitle: '',
  category: '',
  paymentMode: '',
  notes: '',
  balance: 0,
  drCr: '',
}
